backend:
  name: github
  repo: Snehdeep-ts/portfolio
  branch: main
  base_url: https://www.madewithsneh.com
  auth_endpoint: api/auth

media_folder: 'public/images'
public_folder: '/images'
local_backend: false

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Category',
          name: 'category',
          widget: 'select',
          options: ['Tech', 'Development'],
        }
      - { label: 'Labels', name: 'labels', widget: 'list', allow_add: true }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
